name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  # Build regular ZMK firmware
  build-zmk:
    name: Build ZMK
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: "zmk-elchibre/config"
      fallback_binary: "uf2"
      archive_name: "elchibre-zmk"

  # Build ZMK Studio firmware
  build-zmk-studio:
    name: Build ZMK Studio
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: "zmk-studio-elchibre"
      fallback_binary: "uf2"
      archive_name: "elchibre-zmk-studio"
